import type { Lane, Project, Thought } from "./types";

const now = "2026-09-16T12:00:00.000Z";

export const seedProjects: Project[] = [
  {
    id: "proj-role-onboarding",
    name: "New role onboarding",
    domain: "Work",
    status: "active",
    outcome: "Land the first 30 days with a clear map of people, tools, and done.",
    nextAction: "Write the 30-day map: people to meet, tools to learn, what good looks like.",
    focusNext: true,
    focusOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "proj-side-live",
    name: "Side project live ops",
    domain: "Side project",
    status: "active",
    outcome: "Keep the live app healthy while calendar time gets scarce.",
    nextAction: "Check the latest release notes and review pulse.",
    focusNext: true,
    focusOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "proj-growth-loop",
    name: "Weekly growth loop",
    domain: "Side project",
    status: "active",
    outcome: "A weekly growth loop that does not live only in chat scrollback.",
    nextAction: "Promote the current growth thread into this card's lanes.",
    focusNext: true,
    focusOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "proj-idea-queue",
    name: "Idea validations",
    domain: "Ideas",
    status: "active",
    outcome: "Only graduate ideas that earn a project card.",
    nextAction: "Triage tracker rows still on Park vs Pursue.",
    focusNext: false,
    focusOrder: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "proj-writing-cadence",
    name: "Writing cadence",
    domain: "Side project",
    status: "active",
    outcome: "Ship a small writing cadence without turning it into a full-time job.",
    nextAction: "Batch the next five posts on a light week.",
    focusNext: false,
    focusOrder: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "proj-home-ops",
    name: "Household ops",
    domain: "Home",
    status: "active",
    outcome: "Calendar, pickup, and household logistics stay visible.",
    nextAction: "Capture upcoming event dates onto this card.",
    focusNext: false,
    focusOrder: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "proj-training-block",
    name: "Training block",
    domain: "Health",
    status: "active",
    outcome: "Stay training-capable without turning health into a dashboard.",
    nextAction: "Put this week's sessions on the card.",
    focusNext: false,
    focusOrder: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "proj-finance-thesis",
    name: "Investment thesis",
    domain: "Finance",
    status: "tabled",
    outcome: "One thesis, parked until bandwidth exists after onboarding.",
    nextAction: "Leave it tabled. Reopen after week 4.",
    focusNext: false,
    focusOrder: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "proj-career-narrative",
    name: "Career narrative",
    domain: "Career",
    status: "active",
    outcome: "A crisp story for the next conversation, not a full rebrand.",
    nextAction: "Draft three bullets: win, scope, what you want next.",
    focusNext: false,
    focusOrder: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "proj-inspired-shelf",
    name: "Inspired shelf",
    domain: "Ideas",
    status: "inspired",
    outcome: "Park sparks without pretending they are active work.",
    nextAction: "Skim once a month. Promote only what still pulls.",
    focusNext: false,
    focusOrder: null,
    createdAt: now,
    updatedAt: now,
  },
];

export const seedLanes: Lane[] = [
  {
    id: "lane-onboarding-doc",
    projectId: "proj-role-onboarding",
    laneType: "Doc",
    label: "30-day map",
    urlOrHint: "docs/onboarding-30-day",
  },
  {
    id: "lane-side-repo",
    projectId: "proj-side-live",
    laneType: "Repo",
    label: "App repo",
    urlOrHint: "github.com/you/side-project",
  },
  {
    id: "lane-growth-bot",
    projectId: "proj-growth-loop",
    laneType: "Grok Bot",
    label: "Growth bot",
    urlOrHint: "Growth chat",
  },
  {
    id: "lane-home-cal",
    projectId: "proj-home-ops",
    laneType: "Sheet",
    label: "Family calendar",
    urlOrHint: "shared calendar",
  },
];

export const seedThoughts: Thought[] = [
  {
    id: "thought-idea-newsletter",
    kind: "idea",
    body: "A tiny weekly digest of what moved in Focus next.",
    domain: "Ideas",
    projectId: null,
    createdAt: now,
  },
  {
    id: "thought-todo-books",
    kind: "todo",
    body: "Order the two books recommended for onboarding week 1.",
    domain: "Work",
    projectId: null,
    createdAt: now,
  },
  {
    id: "thought-note-growth",
    kind: "idea",
    body: "Growth loop should end with one shippable experiment, not a longer backlog.",
    domain: "Side project",
    projectId: "proj-growth-loop",
    createdAt: now,
  },
];

export function inboxThoughts(thoughts: Thought[]): Thought[] {
  return thoughts.filter((thought) => thought.projectId === null);
}
