import type { Lane, Project, Thought } from "./types";

const now = "2026-09-17T12:00:00.000Z";

export const seedProjects: Project[] = [
  {
    id: "proj-role-onboarding",
    name: "New role onboarding",
    domain: "Work",
    status: "active",
    outcome: "Land the first 30 days with a clear map of people, tools, and done.",
    nextAction: "Write the 30-day map: people to meet, tools to learn, what good looks like.",
    focusNext: true,
    focusOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "proj-side-live",
    name: "Side project live ops",
    domain: "Side project",
    status: "active",
    outcome: "Keep the live app healthy while calendar time gets scarce.",
    nextAction: "Check the latest release notes and review pulse.",
    focusNext: true,
    focusOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "proj-growth-loop",
    name: "Weekly growth loop",
    domain: "Side project",
    status: "active",
    outcome: "A weekly growth loop that does not live only in chat scrollback.",
    nextAction: "Promote the current growth thread into this card's lanes.",
    focusNext: true,
    focusOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "proj-idea-queue",
    name: "Idea validations",
    domain: "Ideas",
    status: "active",
    outcome: "Only graduate ideas that earn a project card.",
    nextAction: "Triage tracker rows still on Park vs Pursue.",
    focusNext: false,
    focusOrder: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "proj-writing-cadence",
    name: "Writing cadence",
    domain: "Side project",
    status: "active",
    outcome: "Ship a small writing cadence without turning it into a full-time job.",
    nextAction: "Batch the next five posts on a light week.",
    focusNext: false,
    focusOrder: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "proj-home-ops",
    name: "Household ops",
    domain: "Home",
    status: "active",
    outcome: "Calendar, pickup, and household logistics stay visible.",
    nextAction: "Capture upcoming event dates onto this card.",
    focusNext: false,
    focusOrder: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "proj-training-block",
    name: "Training block",
    domain: "Health",
    status: "active",
    outcome: "Stay training-capable without turning health into a dashboard.",
    nextAction: "Put this week's sessions on the card.",
    focusNext: false,
    focusOrder: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "proj-finance-thesis",
    name: "Investment thesis",
    domain: "Finance",
    status: "tabled",
    outcome: "One thesis, parked until bandwidth exists after onboarding.",
    nextAction: "Leave it tabled. Reopen after week 4.",
    focusNext: false,
    focusOrder: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "proj-role-wrap",
    name: "Previous role wrap",
    domain: "Career",
    status: "tabled",
    outcome: "Leave cleanly. Knowledge transfer done. No lingering fire drills.",
    nextAction: "Parked. Only reopen if a wrap item actually pings.",
    focusNext: false,
    focusOrder: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "proj-wiki-inspired",
    name: "Personal wiki experiment",
    domain: "Ideas",
    status: "inspired",
    outcome: "Inspired, not now. A wiki is a different product from this wedge.",
    nextAction: "Keep inspired. Do not build it inside Focus OS.",
    focusNext: false,
    focusOrder: null,
    createdAt: now,
    updatedAt: now,
  },
];

export const seedLanes: Lane[] = [
  {
    id: "lane-onboarding-bot",
    projectId: "proj-role-onboarding",
    laneType: "Grok Bot",
    label: "Onboarding thread",
    urlOrHint:
      "Current chat. Split to a role-only bot if onboarding context gets messy.",
  },
  {
    id: "lane-onboarding-doc",
    projectId: "proj-role-onboarding",
    laneType: "Doc",
    label: "First 30 days notes",
    urlOrHint: "Create a doc when the 30-day map starts.",
  },
  {
    id: "lane-side-repo",
    projectId: "proj-side-live",
    laneType: "Repo",
    label: "App repo",
    urlOrHint: "github.com/example/side-project",
  },
  {
    id: "lane-growth-bot",
    projectId: "proj-growth-loop",
    laneType: "Grok Bot",
    label: "Growth loop",
    urlOrHint: "Durable growth role bot. Open this lane, do not hunt scrollback.",
  },
  {
    id: "lane-ideas-sheet",
    projectId: "proj-idea-queue",
    laneType: "Sheet",
    label: "Idea tracker",
    urlOrHint: "Park / Validate / Inspired.",
  },
  {
    id: "lane-home-doc",
    projectId: "proj-home-ops",
    laneType: "Doc",
    label: "Household calendar scratch",
    urlOrHint: "Family notes live here, not in work chat.",
  },
  {
    id: "lane-finance-bot",
    projectId: "proj-finance-thesis",
    laneType: "Grok Bot",
    label: "Finance thread",
    urlOrHint: "Parked thesis talk lives here, not on the growth loop card.",
  },
];

export const seedThoughts: Thought[] = [
  {
    id: "thought-onboarding-bot",
    body: "Should onboarding get its own chat lane, or stay on the growth bot for week one?",
    projectId: null,
    kind: "idea",
    createdAt: now,
  },
  {
    id: "thought-home-dates",
    body: "Fall event dates need a home on the household ops card.",
    projectId: null,
    kind: "todo",
    createdAt: now,
  },
  {
    id: "thought-writing-batch",
    body: "Batch a writing reminder for the week the new role starts.",
    projectId: "proj-writing-cadence",
    kind: "todo",
    createdAt: now,
  },
];

export function inboxThoughts(thoughts: Thought[]): Thought[] {
  return thoughts.filter((thought) => thought.projectId === null);
}
